#!/usr/bin/env zsh

if [[ $k8s_debug == "ON" ]]; then
  set -x
fi

if [[ $k8s_session_aware == "ON" ]]; then
  k9s --context $k8s_context -n $k8s_namespace
else
  k9s
fi

if [[ $k8s_debug == "ON" ]]; then
  set +x
fi

exit $ret
