#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

source "${HOME}/.zgen/zgen.zsh"
# if the init scipt doesn't exist
if ! zgen saved; then
  # specify plugins here
  zgen load prezto
  zgen load zazab/zsh-fastcd
  zgen load $HOME/.zfunc

  # generate the init script from plugins above
  zgen save
fi

zgen prezto

# Customize to your needs...
 
unsetopt correct
unsetopt correct_all
unsetopt global_rcs

setopt menu_complete

for f in ~/.zsh/alias.d/*.sh; do
    source $f
done

for f in ~/.zsh/custom.d/*.sh; do
    source $f
done

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.iterm2_shell_integration ] && source ~/.iterm2_shell_integration.zsh

stty -ixon
