---
- name: configure vim
  hosts: all
  become: false
  roles:
    - role: vim
      tags:
        - vim
    - role: zsh
      tags:
        - zsh
    - role: git
      tags:
        - git
...
# vim: ts=2 sts=1 sw=2
