---
- name: configure vim
  hosts: all
  become: false
  roles:
    - role: vim
      tags:
        - vim
    - role: brew
      tags:
        - brew
      when: ansible_facts['os_family'] == "Darwin"
    - role: zsh
      tags:
        - zsh
    - role: scripts
      tags:
        - scripts
    - role: git
      tags:
        - git
    - role: tmux
      tags:
        - tmux
...
# vim: ts=2 sts=1 sw=2
