---
terminal_multiplexer: tmux
ghostty_config_dir: "{{ ansible_facts['user_dir'] }}/Library/Application Support/com.mitchellh.ghostty"
terminal_multiplexer_programs:
  Darwin:
    tmux: /opt/homebrew/bin/tmux
    zellij: /opt/homebrew/bin/zellij
  Debian:
    tmux: /usr/bin/tmux
    zellij: "{{ ansible_facts['user_dir'] }}/.local/bin/zellij"
