---
- name: include os specific vars
  include_vars: "{{ansible_os_family}}.yaml"

- name: install zfiles
  copy: 
    src: "zfiles/{{item}}"
    dest: "{{ansible_user_dir}}/.{{item}}"
  with_items:
    - zlogin
    - zlogout
    - zshenv
    - zshrc

- name: install templates
  template:
    src: "{{item}}.j2"
    dest: "{{ansible_user_dir}}/.{{item}}"
  with_items:
    - zpreztorc
    - zprofile

- name: create directories
  file:
    path: "{{ansible_user_dir}}/{{item}}"
    state: directory
  with_items:
    - .zsh
    - .zsh/alias.d
    - .zsh/custom.d
    - .zsh/zshrc.d
    - .zsh/profile.d
    - .zsh/completion_generators
    - .zsh/generated_completions.d
    - .zfunc

- name: install dependencies
  include_tasks: "install_deps_{{ ansible_os_family }}.yaml"

- name: copy custom configs
  copy:
    src: "custom.d/{{item}}.zsh"
    dest: "{{ansible_user_dir}}/.zsh/custom.d/{{item | basename}}.zsh"
    mode: 0644
    directory_mode: yes
  with_items:
    - "{{custom_items}}"

- name: copy .d items
  copy:
    src: "{{item}}.zsh"
    dest: "{{ansible_user_dir}}/.zsh/{{item}}.zsh"
    mode: 0644
    directory_mode: yes
  with_items:
    - alias.d/aliases
    - alias.d/ansible
    - alias.d/avito-tool
    # - alias.d/common
    - alias.d/docker
    - alias.d/fzfcd
    - alias.d/git
    - alias.d/global
    - alias.d/grep
    - alias.d/k8s
    - alias.d/k8s_session_config
    - alias.d/ssh
    - profile.d/fzf
    - profile.d/zsh_autosuggestions
    - zshrc.d/alias_expand
    - zshrc.d/completion_generator
    - zshrc.d/history
    - zshrc.d/iterm
    # - zshrc.d/local_kubectl
    - zshrc.d/p10k
    - zshrc.d/rvm

- name: templated .d items
  template:
    src: "{{item}}.j2"
    dest: "{{ansible_user_dir}}/.zsh/{{item}}.zsh"
    mode: 0644
    directory_mode: yes
  with_items:
    - zshrc.d/fzf

- name: completion generators
  copy:
    dest: "{{ansible_user_dir}}/.zsh/completion_generators/generate_{{item.name}}.zsh"
    mode: 0744
    content: "{{item.cmd}}\n"
  with_items:
    - name: avito
      cmd: avito completion zsh
    - name: iack
      cmd: iack completion bash
    - name: kubectl
      cmd: kubectl completion zsh

- name: install zgen
  git:
    repo: "https://github.com/tarjoilija/zgen.git"
    dest: "{{ansible_user_dir}}/.zgen"
    clone: yes
    update: yes


- name: find zsh-autosuggestions script
  command:
    cmd: find {{packages_path}}/zsh-autosuggestions -name zsh-autosuggestions.zsh
  register: zsh_autosuggestions_path

- name: symlink zsh autosuggestions
  file:
    dest: "{{ansible_user_dir}}/.zsh/zshrc.d/zsh-autosuggestions.zsh"
    src: "{{zsh_autosuggestions_path.stdout}}"
    state: link

...
# vim: ts=2 sts=1 sw=2
