---
- name: install zfiles
  copy: 
    src: "zfiles/{{item}}"
    dest: "{{ansible_user_dir}}/.{{item}}"
  with_items:
    - zlogin
    - zlogout
    - zshenv
    - zshrc

- name: install templates
  template:
    src: "{{item}}.j2"
    dest: "{{ansible_user_dir}}/.{{item}}"
  with_items:
    - zpreztorc
    - zprofile

- name: create directories
  file:
    path: "{{ansible_user_dir}}/{{item}}"
    state: directory
  with_items:
    - .zsh
    - .zsh/alias.d
    - .zsh/custom.d
    - .zsh/profile.d
    - .zfunc

- name: copy custom configs
  copy:
    src: "{{item}}"
    dest: "{{ansible_user_dir}}/.zsh/custom.d/{{item | basename}}"
    mode: 0644
    directory_mode: yes
  with_items:
    - "{{custom_items}}"

- name: copy .d items
  copy:
    src: "{{item}}.zsh"
    dest: "{{ansible_user_dir}}/.zsh/{{item}}.zsh"
    mode: 0644
    directory_mode: yes
  with_items:
    - alias.d/aliases
    - alias.d/ansible
    - alias.d/common
    - alias.d/docker
    - alias.d/fzfcd
    - alias.d/git
    - alias.d/global
    - alias.d/grep
    - alias.d/k8s
    - alias.d/avito-tool
    - profile.d/fzf
    - profile.d/twine
    - profile.d/virtualenv_wrapper
    - zshrc.d/alias_expand
    - zshrc.d/fzf
    - zshrc.d/iterm
    - zshrc.d/k8s
    - zshrc.d/p10k

- name: install zgen
  git:
    repo: "https://github.com/tarjoilija/zgen.git"
    dest: "{{ansible_user_dir}}/.zgen"
    clone: yes
    update: yes

...
# vim: ts=2 sts=1 sw=2
