---
- name: install zfiles
  copy: 
    src: "{{item}}"
    dest: "{{ansible_user_dir}}/.{{item}}"
  with_items:
    - zlogin
    - zlogout
    - zprofile
    - zshenv
    - zshrc

- name: install zprofile
  template:
    src: zpreztorc.j2
    dest: "{{ansible_user_dir}}/.zpreztorc"
 
- name: create directories
  file:
    path: "{{ansible_user_dir}}/{{item}}"
    state: directory
  with_items:
    - .zsh
    - .zsh/alias.d
    - .zfunc

- name: copy custom configs
  copy:
    src: "{{item}}"
    dest: "{{ansible_user_dir}}/.zsh/custom.d/{{item | basename}}"
    mode: 0644
    directory_mode: yes
  with_items:
    - "{{custom_items}}"

- name: copy alias.d items
  copy:
    src: "{{item}}"
    dest: "{{ansible_user_dir}}/.zsh/alias.d/{{item | basename}}"
    mode: 0644
    directory_mode: yes
  with_items:
    - alias.d/aliases.sh
    - alias.d/chef.sh
    - alias.d/fastcd.sh
    - alias.d/common.sh
    - alias.d/docker.sh
    - alias.d/git.sh
    - alias.d/grep.sh
    - alias.d/ssh.sh
    - alias.d/systemd.sh
    - alias.d/ansible.sh

- name: install zgen
  git:
    repo: "https://github.com/tarjoilija/zgen.git"
    dest: "{{ansible_user_dir}}/.zgen"
    clone: yes
    update: yes

...
# vim: ts=2 sts=1 sw=2
