---
common_packages:
  - zsh
  - neovim
  - tree
  - fzf
  - fd
  - sift
  - grc
  - pyenv
  - pyenv-virtualenv
  - go
  - node
  - gnupg
  - gpg
  - tilt
  - watch
  - telnet
  - tcptraceroute
  - alacritty # terminal app
  - eza # ls superpower substitute
  - jq
  - yq
  - miller
custom_packages:
  - kind
  - k9s
  - kustomize
casks:
  - font-fira-mono-nerd-font
  - font-iosevka
  - font-meslo-lg-nerd-font
  - font-hack-nerd-font
  - font-iosevka-nerd-font
...