---
- name: put configs
  copy:
    src: "{{item}}"
    dest: $HOME/.{{item}}
  with_items:
    - gitignore_global

- name: create githooks dir
  file:
    path:     $HOME/.git/template/hooks
    state:    directory
    recurse:  true
    mode:     0755

- name: put githooks
  copy:
    src: "templates/hooks/{{item}}"
    dest: "$HOME/.git/template/hooks/{{item}}"
  with_items:
    - prepare-commit-msg

- name: compile templates
  template:
    src: "{{item}}.j2"
    dest: $HOME/.{{item}}
  with_items:
    - gitconfig
...
# vim: ts=2 sts=1 sw=2