# Generated by sakctl sa shell zsh
eval "$(sakctl sa env --shell zsh)"

alias k="sakctl"
alias kt="sakctl"
alias kraw="kubectl"

kenv() { sakctl sa env "$@"; }
ksa() { eval "$(sakctl sa session toggle --shell zsh)"; sakctl sa env; }
ksaon() { eval "$(sakctl sa session on --shell zsh)"; sakctl sa env; }
ksaoff() { eval "$(sakctl sa session off --shell zsh)"; sakctl sa env; }
ktd() { eval "$(sakctl sa debug toggle --shell zsh)"; sakctl sa env; }

ksc() { eval "$(sakctl sa context set "$@" --shell zsh)"; sakctl sa env; }
ksn() { eval "$(sakctl sa namespace set "$@" --shell zsh)"; sakctl sa env; }
ksnd() { eval "$(sakctl sa namespace default --shell zsh)"; sakctl sa env; }
ksch() { eval "$(sakctl sa context history select "$@" --shell zsh)"; sakctl sa env; }
kch() { sakctl sa context history "$@"; }
kcb() { eval "$(sakctl sa context back --shell zsh)"; sakctl sa env; }
ksac() { eval "$(sakctl sa app-context set "$@" --shell zsh)"; sakctl sa env; }

kcpush() {
  eval "$(sakctl sa session push --shell zsh)"
  sakctl sa env
}
kcpop() {
  eval "$(sakctl sa env --shell zsh)"
  sakctl sa env
}
alias kcreload="kcpop"
