ssh-add -K >/dev/null 2>&1

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

source "${HOME}/.zgen/zgen.zsh"
# if the init scipt doesn't exist
if ! zgen saved; then
  # specify plugins here
  zgen load prezto

  # generate the init script from plugins above
  zgen save
fi

zgen prezto

# Customize to your needs...
unsetopt correct
unsetopt correct_all
unsetopt global_rcs

setopt menu_complete
setopt AUTO_PUSHD

for f in ~/.zsh/alias.d/*.zsh; do
    source $f
done

for f in ~/.zsh/zshrc.d/*.zsh; do
    source $f
done

for f in ~/.zsh/custom.d/*.zsh; do
    source $f
done

for f in ~/.zsh/profile.d/*.zsh; do
    source $f
done

# stty -ixon
