#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

source "${HOME}/.zgen/zgen.zsh"
# if the init scipt doesn't exist
if ! zgen saved; then
  # specify plugins here
  zgen load prezto

  # generate the init script from plugins above
  zgen save
fi

zgen prezto

# Customize to your needs...
unsetopt correct
unsetopt correct_all
unsetopt global_rcs

setopt menu_complete
setopt AUTO_PUSHD

for f in ~/.zsh/alias.d/*.zsh; do
    source $f
done

for f in ~/.zsh/zshrc.d/*.zsh; do
    source $f
done

for f in ~/.zsh/custom.d/*.zsh; do
    source $f
done

stty -ixon
